use_frameworks!

platform :ios, '8.0'

target 'WcjTreeTableLib_Example' do
  pod 'WcjTreeTableLib', :path => '../'

  target 'WcjTreeTableLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
